const cohortMappings: Record<string, string> = {
  c1: '1st Year Computing',
  c2: '2nd Year Computing',
  c3: '3rd Year Computing',
  c4: '4th Year Computing',
  j1: '1st Year JMC',
  j2: '2nd Year JMC',
  j3: '3rd Year JMC',
  j4: '4th Year JMC',
  i2: '2nd Year Information Systems Engineering',
  i3: '3rd Year Information Systems Engineering',
  i4: '4th Year Information Systems Engineering',
  o1: '1st Year Occasionals',
  o2: '2nd Year Occasionals',
  o3: '3rd Year Occasionals',
  o4: '4th Year Occasionals',
  o5: "Exchange Students MSc's",
  o6: "Exchange Students PhD's",
  x1: '1st Year B/MEng External Departments',
  x2: '2nd Year B/MEng External Departments',
  x3: '3rd Year B/MEng External Departments',
  x4: '4th Year MEng External Departments',
  x5: 'MSc External Departments',
  x6: 'PhDs External Departments',
  a5: 'MSc in Advanced Computing',
  q5: 'MRes AI',
  s5: 'MSc in Computer Science (Specialism)',
  t5: 'MSc in Artificial Intelligence',
  v5: 'MSc in Computer Science',
  r6: 'Philosophical Doctorate',
}
export default cohortMappings
