const cohorts: Record<string, string> = {
  c1: '1st Year Computing',
  c2: '2nd Year Computing',
  c3: '3rd Year Computing',
  c4: '4th Year Computing',
  j1: '1st Year Mathematics and Computer Science',
  j2: '2nd Year Mathematics and Computer Science',
  j3: '3rd Year Mathematics and Computer Science',
  j4: '4th Year Mathematics and Computer Science',
  i2: '2nd Year Information Systems Engineering',
  i3: '3rd Year Information Systems Engineering',
  i4: '4th Year Information Systems Engineering',
  o1: '1st Year Exchange Students',
  o2: '2nd Year Exchange Students',
  o3: '3rd Year Exchange Students',
  o4: '4th Year Exchange Students',
  o5: "Exchange Students MSc's",
  o6: "Exchange Students PhD's",
  occ: 'Occasional and Erasmus Students',
  e4: '4th Year Electrical Engineering',
  a5: 'MSc in Advanced Computing',
  v5: 'MSc in Computer Science',
  s5: 'MSc in Computer Science Specialist',
  t5: 'MSc in Artificial Intelligence',
  h5: 'MRes High Performance Embedded and Distributed Systems (HiPEDS)',
  q5: 'MRes AI',
  r5: 'MRes in Advanced Computing',
  y5: 'MSc for Industry',
  b5: 'MSc in Bioinformatics',
  x1: '1st Year B/MEng External Departments',
  x2: '2nd Year B/MEng External Departments',
  x3: '3rd Year B/MEng External Departments',
  x4: '4th Year MEng External Departments',
  x5: 'MSc External Departments',
  x6: 'PhDs External Departments',
  r6: 'Philosophical Doctorate',
  ext: 'External Departments',
  phd: 'Philosophical Doctorate',
}

export default cohorts
